process.env.EMAIL_SERVICE = "aws";
process.env.SMS_SERVICE = "mutlucell";
process.env.PASSWORD_REGEX = "(?=.*[A-Z])(?=.*[a-z]).*";
process.env.SMTP_HOST = "localhost";
process.env.SMTP_USER = "test";
process.env.SMTP_PASSWORD = "test";
process.env.JWT_ALGORITHM = "HS256";
process.env.JWT_AUDIENCE = "test";
process.env.JWT_ISSUER = "test";
process.env.JWT_SECRET = "test";
process.env.MUTLUCELL_API_URL = "test";
process.env.MUTLUCELL_USERNAME="test";
process.env.MUTLUCELL_PASSWORD="test";
process.env.MUTLUCELL_ORIGINATOR="test";
