version: '3.3'
services:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
volumes:
  postgres-data: