name: NPM Release
on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: action-test
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      JWT_ALGORITHM: ${{ vars.JWT_ALGORITHM }}
      JWT_AUDIENCE: ${{ vars.JWT_AUDIENCE }}
      JWT_ISSUER: ${{ vars.JWT_AUDIENCE }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14.19.2"
      - run: npm install
      - run: npm run test
      - run: npm run test:e2e
  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14.19.2"
      - run: npm install
      - run: npm run build
      - run: cd dist
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
