name: sonarcloud
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            JWT_ALGORITHM: ${{ vars.JWT_ALGORITHM }}
            JWT_AUDIENCE: ${{ vars.JWT_AUDIENCE }}
            JWT_ISSUER: ${{ vars.JWT_ISSUER }}
            JWT_SECRET: ${{ vars.JWT_SECRET }}
      - name: echo
        run: echo ${{ secrets.JWT_SECRET }}
      - name: echo
        run: echo ${{ vars.JWT_SECRET }}
      - name: echo
        run: echo ${{ env.JWT_SECRET }}
      - name: Install dependencies
        run: yarn install
      - name: Test E2E
        run: yarn test:e2e
      - name: Test and coverage
        run: yarn test:cov
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master

