name: sonarcloud
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    environment: sonarcloud
    env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            JWT_ALGORITHM: ${{ vars.JWT_ALGORITHM }}
            JWT_AUDIENCE: ${{ vars.JWT_AUDIENCE }}
            JWT_ISSUER: ${{ vars.JWT_AUDIENCE }}
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - uses: actions/setup-node@v3
        with:
          # Version Spec of the version to use in SemVer notation.
          # It also emits such aliases as lts, latest, nightly and canary builds
          # Examples: 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly, latest, node
          node-version: "16.x"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      - name: Test E2E
        run: npm run test:e2e
      - name: Test and coverage
        run: npm run test:cov
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master

